import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import SideNav from '@/components/layout/sidenav'
import Header from '@/components/layout/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex">
          <SideNav />
          <div className="w-full overflow-x-auto">
            <div className="overflow-auto sm:h-[calc(99vh-60px)]">
              <div className="h-[calc(100vh - 120px)] relative mx-auto flex w-full justify-center overflow-auto overflow-y-auto">
                <div className="w-full md:max-w-7xl">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
